# Generated by Django 5.0.6 on 2024-06-26 09:48

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chatgroup_groupmessage_delete_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=122, unique=True),
        ),
    ]
